version: '3'

tasks:
  run:
    cmds:
      - task watch -- go run ./examples

  demo:
    cmds:
      - task watch -- go run ./examples/std_http

  watch:
    cmds:
      - |
        reflex -r '\.go' -s -- sh -c '{{.CLI_ARGS}}'

  test:
    cmds:
      - go test -count=1 -v ./...

  lint:docker:
    cmds:
      - docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.54.0 golangci-lint run -v

  lint:
    cmds:
      - golangci-lint run