version: '3'

tasks:
  build:
    cmds:
      - go build -o ./bin/http_v0_9 ./cmd

  run:
    cmds:
      - task watch -- go run ./cmd -port=8080 -root=./static

  watch:
    cmds:
      - |
        reflex -r '\.go' -s -- sh -c '{{.CLI_ARGS}}'

  test:
    cmds:
      - go test -count=1 -v ./client/...