version: '3'

tasks:
  build:
    cmds:
      - go build -o ./bin/http_v1_1 ./cmd

  run:
    cmds:
      - task watch -- go run ./cmd

  demo:
    cmds:
      - task watch -- go run ./demo

  watch:
    cmds:
      - |
        reflex -r '\.go' -s -- sh -c '{{.CLI_ARGS}}'

  test:
    cmds:
      - go test -count=1 -v ./client/...